Clone github repo:

In [1]:
%cd /content
import os
from getpass import getpass
user = 'hczhai'
pw = getpass('Password: ')
os.system('git clone https://{}:{}@github.com/block-hczhai/pyblock3.git'.format(user, pw))
del pw

/content
Password: ··········


In [2]:
%cd pyblock3

/content/pyblock3


Construct MPO:

In [13]:
from pyblock3.algebra.core import SparseTensor
from pyblock3.algebra.symmetry import SZ, BondInfo
from pyblock3.algebra.mps import MPSInfo, MPS
from pyblock3.fcidump import FCIDUMP
from pyblock3.symbolic.symbolic_mpo import QCSymbolicMPO
from pyblock3.hamiltonian import QCHamiltonian
import pyblock3.algebra.funcs as pbalg

fd = 'data/HUBBARD-L8.FCIDUMP'
fcidump = FCIDUMP(pg='d2h').read(fd)
hamil = QCHamiltonian(fcidump)
mpo = QCSymbolicMPO(hamil).to_sparse()

In [14]:
print(mpo[0].__class__)
mpo[0]

<class 'pyblock3.algebra.core.FermionTensor'>


 ODD-  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[[1. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. ]]]])
 ODD-  1 (Q=) (< N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[[1. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. ]]]])
 ODD-  2 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[[1. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. ]]]])
 ODD-  3 (Q=) (< N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[[-1. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]]]])
 ODD-  4 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=-1 SZ=-1/2 PG=0 >) (R=) array([[[[ 1. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]]]])
 ODD-  5 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=2 SZ=0 PG=0 >, < N=-1 SZ=-1/2 PG=0 >) (R=) array([[[[ 1. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ]]]])
 ODD-  6 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=

Construct MPS:

In [15]:
mps_info = MPSInfo(hamil.n_sites, hamil.vacuum, hamil.target, hamil.basis)
mps_info.set_bond_dimension_fci()
mps_info.set_bond_dimension(100)
mps = MPS.random(mps_info)

In [16]:
print(mps[0].__class__)
mps[0]

<class 'pyblock3.algebra.core.SparseTensor'>


  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[[0.60510428]]])
  1 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[0.77893528]]])
  2 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[0.91865902]]])
  3 (Q=) (< N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[0.14380205]]])

MPO/MPS algebra:

In [17]:
import numpy as np
np.dot(mps, mpo @ mps)

38751646.82385999

Block-sparse tensor algebra:

In [18]:
np.tensordot(mps[0], mps[1], axes=1)

  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[[[0.03758163]]]])
  1 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[[0.15936207, 0.52263863]]]])
  2 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[[0.60379297, 0.2836531 ]]]])
  3 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[[0.09766495, 0.31217308, 0.46543782, 0.55732633]]]])
  4 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[[0.410195  , 0.59455824]]]])
  5 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=2 SZ=-1 PG=0 >) (R=) array([[[[0.08474924]]]])
  6 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[[0.2240428 , 0.4063493 , 0.36127595, 0.17125435]]]])
  7 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG

In [19]:
pbalg.hdot(mps[0], mps[1]).n_blocks

16

MPS canonicalization:

In [20]:
print("MPS = ", mps.show_bond_dims())
mps = mps.canonicalize(center=0)
mps /= mps.norm()
print("MPS = ", mps.show_bond_dims())

MPS =  1|4|16|64|115|64|16|4|1
MPS =  1|4|16|64|115|64|16|4|1


In [21]:
np.dot(mps, mps)

0.9999999999999999

MPO Compression:

In [22]:
print("MPO = ", mpo.show_bond_dims())
mpo, _ = mpo.compress(left=True, cutoff=1E-12, norm_cutoff=1E-12)
print("MPO = ", mpo.show_bond_dims())

MPO =  1|46|82|142|226|334|466|622|1
MPO =  1|6|6|6|6|6|6|6|1


Build SparseTensor:

In [23]:
hamil.basis[0]

BondInfo({< N=0 SZ=0 PG=0 >: 1,
          < N=1 SZ=-1/2 PG=0 >: 1,
          < N=1 SZ=1/2 PG=0 >: 1,
          < N=2 SZ=0 PG=0 >: 1})

In [24]:
SparseTensor.zeros((hamil.basis[0], hamil.basis[0]))

  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[0.]])
  1 (Q=) (< N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[0.]])
  2 (Q=) (< N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[0.]])
  3 (Q=) (< N=2 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[0.]])

In [25]:
SparseTensor.zeros((hamil.basis[0], hamil.basis[0]), dq=SZ(1, -1, 0))

  0 (Q=) (< N=1 SZ=-1/2 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[0.]])
  1 (Q=) (< N=2 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[0.]])

In [26]:
SparseTensor.zeros((hamil.basis[0], hamil.basis[0]), dq=SZ(1, -1, 0)).transpose()

  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[0.]])
  1 (Q=) (< N=1 SZ=1/2 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[0.]])

In [27]:
SparseTensor.zeros((hamil.basis[0], hamil.basis[0], hamil.basis[0]), pattern='++-')

  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[[0.]]])
  1 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[0.]]])
  2 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[0.]]])
  3 (Q=) (< N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[0.]]])
  4 (Q=) (< N=1 SZ=-1/2 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[0.]]])
  5 (Q=) (< N=1 SZ=-1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[0.]]])
  6 (Q=) (< N=1 SZ=1/2 PG=0 >, < N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[0.]]])
  7 (Q=) (< N=1 SZ=1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[0.]]])
  8 (Q=) (< N=2 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[0.]]])

In [28]:
info = BondInfo({SZ(1, -1, 0): 2, SZ(-1, 1, 0): 3, SZ(0, 0, 0): 2})

In [29]:
a = SparseTensor.random((info, info), dq=SZ(1, -1, 0))
a

  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=-1 SZ=1/2 PG=0 >) (R=) array([[0.47729531, 0.48417595, 0.8279901 ],
       [0.24426988, 0.57768827, 0.20252976]])
  1 (Q=) (< N=1 SZ=-1/2 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[0.88366471, 0.27082862],
       [0.78864662, 0.84848856]])

In [30]:
a.T

  0 (Q=) (< N=-1 SZ=1/2 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[0.47729531, 0.24426988],
       [0.48417595, 0.57768827],
       [0.8279901 , 0.20252976]])
  1 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[0.88366471, 0.78864662],
       [0.27082862, 0.84848856]])

DMRG (slow):

In [31]:
from pyblock3.moving_environment import MovingEnvironment
from functools import reduce
import time

mps.opts = dict(cutoff=1E-12, norm_cutoff=1E-12, max_bond_dim=200)
me = MovingEnvironment(mps, mpo, mps)

In [32]:
def dmrg(n_sweeps=10, tol=1E-6, dot=1):
    eners = np.zeros((n_sweeps, ))
    for iw in range(n_sweeps):
        print("Sweep = %4d | Direction = %8s | Bond dimension = %4d" % (
            iw, "backward" if iw % 2 else "forward", me.ket.opts["max_bond_dim"]))
        for i in range(0, me.n_sites - dot + 1)[::(-1) ** iw]:
            tt = time.perf_counter()
            eff = me[i:i + dot]
            eff.ket[:] = [reduce(pbalg.hdot, eff.ket[:])]
            eners[iw], eff, ndav = eff.eigh(iprint=True)
            if dot == 2:
                wfn = eff.ket[0]
                l, s, r = wfn.tensor_svd(
                    idx=3, pattern='+++-++', full_matrices=False)
                eff.ket[:] = [np.tensordot(l, s.diag(), axes=1), r]
            me[i:i + dot] = eff
            print(" %3s Site = %4d-%4d .. Ndav = %4d E = %20.12f T = %8.3f" % (
                "<--" if iw % 2 else "-->", i, i + dot - 1, ndav, eners[iw], time.perf_counter() - tt))
        if abs(reduce(np.subtract, eners[:iw + 1][-2:])) < tol:
            break
    return eners[iw]

In [33]:
tx = time.perf_counter()
print("GS Energy = %20.12f" % dmrg())
print('time = ', time.perf_counter() - tx)

Sweep =    0 | Direction =  forward | Bond dimension =  200
    1     1     0      3.45508676  8.18e-01
    2     2     0      2.74660091  8.55e-01
    3     3     0      1.96699137  3.48e-01
    4     4     0      1.77842278  2.03e-31
 --> Site =    0-   0 .. Ndav =    4 E =       1.778422784916 T =    0.209
    1     1     0      1.77842278  1.92e+00
    2     2     0      0.80601244  9.58e-01
    3     3     0      0.43073337  5.52e-01
    4     4     0      0.24633072  2.80e-01
    5     5     0      0.15858144  1.36e-01
    6     6     0      0.10285980  1.37e-01
    7     7     0     -0.07466836  5.35e-01
    8     8     0     -0.41496062  4.06e-01
    9     9     0     -0.54869997  1.05e-01
   10    10     0     -0.58160396  2.24e-02
   11    11     0     -0.58807379  5.60e-03
   12    12     0     -0.58939572  1.01e-03
   13    13     0     -0.58965801  1.55e-04
   14    14     0     -0.58969637  2.04e-05
   15    15     0     -0.58970127  3.38e-06
 --> Site =    1-   1 .. Ndav

Check ground-state energy:

In [34]:
print('MPS energy = ', np.dot(mps, mpo @ mps))

MPS energy =  -6.225633346082411


Check that ground-state MPS is normalized:

In [35]:
print('MPS = ', mps.show_bond_dims())
print('MPS norm = ', mps.norm())

MPS =  1|4|16|64|115|64|16|4|1
MPS norm =  0.9999999999999998


### MPS Scaling

MPS scaling (by scaling the first MPS tensor):

In [36]:
mps.opts = {}
print('2 MPS = ', (2 * mps).show_bond_dims())
print((2 * mps).norm())

2 MPS =  1|4|16|64|115|64|16|4|1
1.9999999999999996


Check the first MPS tensor:

In [37]:
mps[0]

  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[[1.]]])
  1 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[1.]]])
  2 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[1.]]])
  3 (Q=) (< N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[1.]]])

In [38]:
(2 * mps)[0]

  0 (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[[2.]]])
  1 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[2.]]])
  2 (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[2.]]])
  3 (Q=) (< N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[2.]]])

### MPS Addition

MPS addition will increase the bond dimension:

In [39]:
mps_add = mps + mps
print('MPS + MPS = ', mps_add.show_bond_dims())
print(mps_add.norm())

MPS + MPS =  1|8|32|128|230|128|32|8|1
1.9999999999999996


Check the overlap `<2MPS|MPS+MPS>`:

In [40]:
%%time
mps_add @ (2 * mps)

CPU times: user 20.9 ms, sys: 0 ns, total: 20.9 ms
Wall time: 21.9 ms


3.9999999999999982

### MPS Canonicalization

Left canonicalization:

In [41]:
lmps = mps_add.canonicalize(center=mps_add.n_sites - 1)
print('L-MPS = ', lmps.show_bond_dims())

L-MPS =  1|4|16|64|226|128|32|8|1


Right canonicalization:

In [42]:
rmps = mps_add.canonicalize(center=0)
print('R-MPS = ', rmps.show_bond_dims())

R-MPS =  1|8|32|128|226|64|16|4|1


Check the overlap `<LMPS|RMPS>`:

In [43]:
%%time
lmps @ rmps

CPU times: user 24.7 ms, sys: 1.06 ms, total: 25.7 ms
Wall time: 29.2 ms


3.999999999999999

### MPS Compression

Compression will first do canonicalization from left to right, then do SVD from right to left.

This can further decrease bond dimension of MPS.

In [44]:
print('MPS + MPS = ', mps_add.show_bond_dims())
mps_add, _ = mps_add.compress(cutoff=1E-9)
print('MPS + MPS = ', mps_add.show_bond_dims())
print(mps_add.norm())

MPS + MPS =  1|8|32|128|230|128|32|8|1
MPS + MPS =  1|4|16|64|115|64|16|4|1
2.0000000000000004


### MPS Subtraction

Subtractoin will also increase bond dimension:

In [45]:
mps_minus = mps - mps
print('MPS - MPS = ', mps_minus.show_bond_dims())

MPS - MPS =  1|8|32|128|230|128|32|8|1


After compression, this is zero:

In [46]:
mps_minus, _ = mps_minus.compress(cutoff=1E-12)
print('MPS - MPS = ', mps_minus.show_bond_dims())
print(mps_minus.norm())

MPS - MPS =  0|0|0|0|0|0|0|0|0
0.0


### MPS Bond Dimension Truncation

Apply MPO two times to MPS:

In [47]:
%%time
hhmps = mpo @ (mpo @ mps)
print(hhmps.show_bond_dims())
print(np.sqrt(hhmps @ mps))

1|136|560|2272|3924|2272|560|136|1
6.225633682146051
CPU times: user 534 ms, sys: 40.9 ms, total: 575 ms
Wall time: 538 ms


MPS compression can be used to reduce bond dimension (to FCI):

In [49]:
%%time
hhmps, cps_error = hhmps.compress(cutoff=1E-12)
print('error = ', cps_error)
print(hhmps.show_bond_dims())
print(np.sqrt(hhmps @ mps))

error =  0.0
1|4|16|64|256|64|16|4|1
6.225633682146053
CPU times: user 195 ms, sys: 145 ms, total: 340 ms
Wall time: 189 ms


Truncation to bond dimension 100 will introduce a small error:

In [51]:
hhmps, cps_error = hhmps.compress(max_bond_dim=100, cutoff=1E-12)
print('error = ', cps_error)
print(hhmps.show_bond_dims())
print(np.sqrt(hhmps @ mps))

error =  0.0017477317693784886
1|4|16|64|100|64|16|4|1
6.225633681059643


Truncation to bond dimension 30 will introduce a larger error:

In [52]:
hhmps, cps_error = hhmps.compress(max_bond_dim=30, cutoff=1E-12)
print('error = ', cps_error)
print(hhmps.show_bond_dims())
print(np.sqrt(hhmps @ mps))

error =  0.1285172180604722
1|4|16|30|30|30|16|4|1
6.225534612598654


### MPO-MPO Contraction

One can also first contract two MPO:

In [53]:
%%time
h2 = mpo @ mpo
print(h2.show_bond_dims())

1|32|32|32|32|32|32|32|1
CPU times: user 97.5 ms, sys: 350 µs, total: 97.9 ms
Wall time: 98.7 ms


Check expectation value:

In [54]:
%%time
print(np.sqrt((h2 @ mps) @ mps))

6.225633682146051
CPU times: user 437 ms, sys: 48.5 ms, total: 485 ms
Wall time: 441 ms


### MPO Bond Dimension Truncation

Compression MPO (keeping accuracy):

In [55]:
h2, cps_error = h2.compress(cutoff=1E-12)
print('error = ', cps_error)
print(h2.show_bond_dims())
print(np.sqrt((h2 @ mps) @ mps))

error =  7.247580457972392e-13
1|16|17|17|17|17|18|16|1
6.225633682146052


MPO Truncated to bond dimension 15:

In [57]:
h2, cps_error = h2.compress(max_bond_dim=15, cutoff=1E-12)
print('error = ', cps_error)
print(h2.show_bond_dims())
print(np.sqrt((h2 @ mps) @ mps))

error =  173.3586581408118
1|15|15|15|15|15|15|15|1
6.119386304980971


MPO Truncated to bond dimension 12:

In [59]:
h2, cps_error = h2.compress(max_bond_dim=12, cutoff=1E-12)
print('error = ', cps_error)
print(h2.show_bond_dims())
print(np.sqrt((h2 @ mps) @ mps))

error =  221.6966311660231
1|12|12|12|12|12|12|12|1
5.816697950013615


# N2 (10o, 7e) (STO3G)

### Initialization

Get ground-state MPS (from FCIDUMP):

In [60]:
%%time
fd = 'data/N2.STO3G.FCIDUMP'
fcidump = FCIDUMP(pg='d2h').read(fd)
hamil = QCHamiltonian(fcidump)
mpo = QCSymbolicMPO(hamil).to_sparse()

print('MPO (NC) =         ', mpo.show_bond_dims())
mpo, _ = mpo.compress(left=True, cutoff=1E-12, norm_cutoff=1E-12)
print('MPO (compressed) = ', mpo.show_bond_dims())

mps_info = MPSInfo(hamil.n_sites, hamil.vacuum, hamil.target, hamil.basis)
mps_info.set_bond_dimension(250)
mps = MPS.random(mps_info)
mps.opts = dict(cutoff=1E-12, norm_cutoff=1E-12, max_bond_dim=200)

me = MovingEnvironment(mps, mpo, mps)

MPO (NC) =          1|54|90|150|234|342|474|630|810|1014|1 (   +23.57244)
MPO (compressed) =  1|16|42|80|90|80|62|67|30|12|1 (   +23.57244)
CPU times: user 1.39 s, sys: 168 ms, total: 1.56 s
Wall time: 1.38 s


In [61]:
%%time
print("GS Energy = %20.12f" % dmrg())

Sweep =    0 | Direction =  forward | Bond dimension =  200
    1     1     0    -91.01700399  2.79e+01
    2     2     0   -100.43541689  6.49e+01
    3     3     0   -103.16626820  1.59e-03
    4     4     0   -103.16638275  1.01e-26
 --> Site =    0-   0 .. Ndav =    4 E =    -103.166382751812 T =    0.820
    1     1     0   -103.16638275  3.26e-01
    2     2     0   -103.24926215  5.24e-01
    3     3     0   -103.41447785  3.71e+00
    4     4     0   -103.74612858  2.64e-01
    5     5     0   -103.77788935  1.71e-01
    6     6     0   -103.79312215  1.25e-01
    7     7     0   -103.80534068  8.84e-02
    8     8     0   -103.81089202  4.24e-02
    9     9     0   -103.81394551  3.07e-02
   10    10     0   -103.81696851  2.69e-02
   11    11     0   -103.81994611  8.44e-03
   12    12     0   -103.82120610  2.15e-02
   13    13     0   -103.82676713  7.75e-02
   14    14     0   -103.84088571  3.12e-02
   15    15     0   -103.84269323  7.96e-03
   16    16     0   -103.8439

Check MPO:

In [62]:
print('MPO = ', mpo.show_bond_dims())
mpo, error = mpo.compress(cutoff=1E-12)
print('MPO = ', mpo.show_bond_dims())

MPO =  1|16|42|80|90|80|62|67|30|12|1 (   +23.57244)
MPO =  1|16|42|80|90|80|62|67|30|12|1 (   +23.57244)


Check MPS:

In [63]:
print('MPS = ', mps.show_bond_dims())
print(mps.norm())

MPS =  1|4|16|58|106|96|50|30|8|4|1
0.9999999999999996


Check ground-state energy:

In [65]:
%%time
mps @ (mpo @ mps)

CPU times: user 1.7 s, sys: 240 ms, total: 1.94 s
Wall time: 1.68 s


-107.65412136429518

### MPO-MPS Contraction

In [67]:
%%time
mps.opts = {}
hmps = mpo @ mps
print(hmps.show_bond_dims())
print(hmps.norm())

1|68|688|4698|9646|7776|3150|2040|248|52|1
107.65412137543466
CPU times: user 3.03 s, sys: 272 ms, total: 3.3 s
Wall time: 2.35 s


The result MPS can be compressed:

In [68]:
hmps, _ = hmps.compress(cutoff=1E-12)
print(hmps.show_bond_dims())
print(hmps.norm())

1|4|16|58|106|96|50|30|8|4|1
107.65412137543454


MPO truncation to bond dimension 50:

In [70]:
cmpo, cps_error = mpo.compress(max_bond_dim=50, cutoff=1E-12)
print('error = ', cps_error)
print(cmpo.show_bond_dims())

error =  234.66416609498486
1|16|42|50|50|50|50|50|30|12|1 (   +23.57244)


Apply contracted MPO to MPS:

In [71]:
hmps = cmpo @ mps
print(hmps.show_bond_dims())
print(hmps.norm())

1|68|688|2958|5406|4896|2550|1530|248|52|1
107.60510163078064


### Determinants

Using SliceableTensor:

In [77]:
smps = mps.to_sliceable()
print(smps[0])
print('-'*20)
print(smps[0][:, 2:, 2])
print('-'*20)
print(smps[0][:, :2, 2].infos)
print('-'*20)
print(smps[0])
print('-'*20)
print(smps.amplitude([3, 3, 0, 3, 0, 3, 3, 3, 3, 0]))

   [0 0 0] (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[[1.]]])
   [0 1 1] (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[1.]]])
   [0 2 2] (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[1.]]])
   [0 3 3] (Q=) (< N=0 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >, < N=2 SZ=0 PG=0 >) (R=) array([[[1.]]])
--------------------
     [0 0] (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[1.]]])
--------------------
(< N=0 SZ=0 PG=0 > = 1, < N=0 SZ=0 PG=0 > = 1 < N=1 SZ=-1/2 PG=0 > = 1 < N=1 SZ=1/2 PG=0 > = 1 < N=2 SZ=0 PG=0 > = 1, < N=1 SZ=1/2 PG=0 > = 1)
--------------------
   [0 0 0] (Q=) (< N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >, < N=0 SZ=0 PG=0 >) (R=) array([[[1.]]])
   [0 1 1] (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=-1/2 PG=0 >, < N=1 SZ=-1/2 PG=0 >) (R=) array([[[1.]]])
   [0 2 2] (Q=) (< N=0 SZ=0 PG=0 >, < N=1 SZ=1/2 PG=0 >, < N=1 SZ=1/2 PG=0 >) (R=) array([[[1.]]])
   [0 3 3]

If the determinant belongs to another symmetry sector, the overlap should be zero:

In [76]:
print(smps.amplitude([3, 3, 0, 0, 0, 3, 3, 3, 3, 0]))

0


Check the overlap for all doubly occupied determinants:

In [79]:
%%time
import itertools

coeffs = []
for ocp in itertools.combinations(range(10), 7):
    det = [0] * mps.n_sites
    for t in ocp:
        det[t] = 3
    tt = time.perf_counter()
    coeffs.append(smps.amplitude(det))
    print(np.array(det), "%10.5f" % coeffs[-1])

[3 3 3 3 3 3 3 0 0 0]    0.01152
[3 3 3 3 3 3 0 3 0 0]   -0.00187
[3 3 3 3 3 3 0 0 3 0]    0.01151
[3 3 3 3 3 3 0 0 0 3]   -0.00190
[3 3 3 3 3 0 3 3 0 0]    0.01302
[3 3 3 3 3 0 3 0 3 0]   -0.95744
[3 3 3 3 3 0 3 0 0 3]    0.13165
[3 3 3 3 3 0 0 3 3 0]    0.13164
[3 3 3 3 3 0 0 3 0 3]   -0.03860
[3 3 3 3 3 0 0 0 3 3]    0.01307
[3 3 3 3 0 3 3 3 0 0]   -0.00086
[3 3 3 3 0 3 3 0 3 0]    0.01316
[3 3 3 3 0 3 3 0 0 3]   -0.00241
[3 3 3 3 0 3 0 3 3 0]   -0.00240
[3 3 3 3 0 3 0 3 0 3]    0.00056
[3 3 3 3 0 3 0 0 3 3]   -0.00085
[3 3 3 3 0 0 3 3 3 0]    0.05454
[3 3 3 3 0 0 3 3 0 3]   -0.00687
[3 3 3 3 0 0 3 0 3 3]    0.05452
[3 3 3 3 0 0 0 3 3 3]   -0.00687
[3 3 3 0 3 3 3 3 0 0]   -0.00002
[3 3 3 0 3 3 3 0 3 0]    0.00099
[3 3 3 0 3 3 3 0 0 3]   -0.00014
[3 3 3 0 3 3 0 3 3 0]   -0.00014
[3 3 3 0 3 3 0 3 0 3]    0.00004
[3 3 3 0 3 3 0 0 3 3]   -0.00002
[3 3 3 0 3 0 3 3 3 0]    0.00032
[3 3 3 0 3 0 3 3 0 3]   -0.00005
[3 3 3 0 3 0 3 0 3 3]    0.00032
[3 3 3 0 3 0 0 3 3 3]   -0.00005
[3 3 3 0 0

Check the sum of probabilities:

In [80]:
print((np.array(coeffs) ** 2).sum())

0.9626586596915242


# Finite-Temperature DMRG

to be finished...

A block2-assisted version is in tests/ancilla.py